### PR TITLE
release 10 10 2024

### PR DESCRIPTION
**Pull request by TCMeldrum**
Release for incresed cache size

### CODE REVIEW

**Review by ACLay — APPROVED** [review]

**Comment by simonfernandes** [comment]
Could you just hold off merging a sec, we're seeing some dependency issues on other PRs

**Comment by simonfernandes** [comment]
ttlcache isn't added to package-lock.json

**Comment by simonfernandes** [comment]
I think it will be quicker to add to this branch or we might not make the release window

**Comment by simonfernandes** [comment]
Farai is adding it here

**Review by yoganandaness — APPROVED** [review]

**Comment by TCMeldrum** [comment]
@mutambaraf could you remove the yarn lock?

**Comment by TCMeldrum** [comment]
Sorry maybe we needed the yarn lock changes my bad

**Review by simonfernandes — APPROVED** [review]

**Pull request merged**
