### PR TITLE
fix: optimised display of delete, archive, unarchive button

### PR DESCRIPTION
**Pull request by yoganandaness**
## Description

1. Delete button will be visible, if the template is not being used ie., not associated with any other dependencies
2. Archive button will be visible, if the template is being used or not used
3. Unarchive button will be visible, if the template is archived. 

This PR also contains the following fixs

1. In the Proposal template table, where the check for validating if the pdf template is being used by any calls was not correctly configured. 
2. Validating Deletion in ESI Template was incorrect. It was not validating if the ESI template is associated with any call or not. Validation added. 
3. Fap Review template Call count was calculated incorrectly. Fixed. 

## Motivation and Context

Providing uniform experience for Delete, Archive and Unarchive button. 

## How Has This Been Tested

Manually

## Tests included/Docs Updated?

- [ ] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

### CODE REVIEW

**Comment by janosbabik** [comment]
Hi @yoganandaness! Nice fix! Could you cover it with an E2E test?

**Review by janosbabik — CHANGES_REQUESTED** [review]
I have noticed that, you added a yarn.lock file to the project in this PR #748 
Please remove it.

**Comment by yoganandaness** [comment]
@janosbabik i have removed the yarn.lock file. Could you please review it at your convenience.

**Review by deepaksftc — APPROVED** [review]

**Comment by janosbabik** [comment]
@yoganandaness It seems your new e2e tests are failing.

**Comment by yoganandaness** [comment]
> @yoganandaness It seems your new e2e tests are failing.

@janosbabik the test is now passing. Could u pls approve.

**Review by janosbabik — APPROVED** [review]

**Pull request merged**
