### PR TITLE
[WIP]refactor: use shorter names for apps folders to follow better practice

### PR DESCRIPTION
**Pull request by martin-trajanovski**
## Description

Change the `user-office-frontend-e2e` folder name to `user-office-core-e2e` which makes more sense and follows better practice.

## Motivation and Context

The e2e folder name was a bit strange because it is testing the whole application but we call it frontend-e2e.

## How Has This Been Tested

- manual testing
- e2e tests

## Tests included/Docs Updated?

- [x] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

### CODE REVIEW

**Review by mutambaraf — COMMENTED** [review]
We might need to do some changes on our deployment can this wait for us to do the changes.

**Comment by martin-trajanovski** [comment]
> We might need to do some changes on our deployment can this wait for us to do the changes.

Sure no worries. We are not in a hurry with this one.

**Comment by martin-trajanovski** [comment]
Because we want to keep git history this might be postponed little bit so STFC can do their changes at the same time for deployment scripts.

**Comment by martin-trajanovski** [comment]
New PR created https://github.com/UserOfficeProject/user-office-core/pull/342

**Pull request closed without merging**
