### PR TITLE
Proposal pdf filename is changed to RB_SURNAME_YYYY format

### PR DESCRIPTION
**Pull request by deepaksftc**
## Description

Fixes https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/768

## Motivation and Context

As a user officer, I would like the proposal PDF filename changed to RB_SURNAME_YYYY format so that it's easier to manage

## How Has This Been Tested

Manual
e2e tests

## Fixes

https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/768

## Changes

Proposal pdf filename is changed to RB_SURNAME_YYYY format

## Tests included/Docs Updated?

- [x ] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

## Screenshots
image
image
image

### CODE REVIEW

**Comment by bolmsten** [comment]
Talked with our User Officer and this is okay with us

**Review by simonfernandes — APPROVED** [review]

**Review by bolmsten — APPROVED** [review]

**Comment by janosbabik** [comment]
Hi! Do you want me to delete the generated-sdk cache from github action and re-run all jobs. e2e workflow will not fail then.

**Comment by deepaksftc** [comment]
Hi, yes please.

**Comment by deepaksftc** [comment]
> Hi @deepaksftc! Do you want me to delete the generated-sdk cache from github action and re-run all jobs. e2e workflow will not fail then.

**Pull request merged**
