### PR TITLE
feat: add status actions UI in the workflows

### PR DESCRIPTION
**Pull request by martin-trajanovski**
## Description

This PR aims to add the UI part for the status actions in the workflows. Also all the endpoints needed to support the UI work are added.

## Motivation and Context

Status actions were needed as part of the workflow so we can give much more power to the concept of workflow and statuses. Now this is supported by a user friendly UI that can help creating better and more functional proposal workflows.

## How Has This Been Tested

- manual tests
- e2e tests (https://github.com/UserOfficeProject/user-office-core/pull/318)

## Fixes

- https://jira.esss.lu.se/browse/SWAP-3419

## Changes

https://github.com/UserOfficeProject/user-office-core/assets/6333063/2218a977-b675-472f-9063-d6001649fdb2

## Tests included/Docs Updated?

- [x] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

### CODE REVIEW

**Review by RasmiaKulan — APPROVED** [review]

**Review by enthusiastio — COMMENTED** [review]
Hi, I did not finish the review yet, but i encountered an error 
```
react-dom.development.js:9035 Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at insertBefore (http://localhost:3000/static/js/bundle.js:248365:22)
    at insertOrAppendPlacementNode (http://localhost:3000/static/js/bundle.js:257654:11)
    at insertOrAppendPlacementNode (http://localhost:3000/static/js/bundle.js:257664:13)
    at insertOrAppendPlacementNode (http://localhost:3000/static/js/bundle.js:257661:11)
    at insertOrAppendPlacementNode (http://localhost:3000/static/js/bundle.js:257661:11)
    at commitPlacement (http://localhost:3000/static/js/bundle.js:257623:9)
    at commitMutationEffects (http://localhost:3000/static/js/bundle.js:259492:15)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:242885:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:242929:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:242984:35)
```
which seems to go away by commenting out these lines
image
Did you experience something similar?

**Comment by martin-trajanovski** [comment]
> Hi, I did not finish the review yet, but i encountered an error. That happens as soon as I click Add status change events
> 
> ```
> react-dom.development.js:9035 Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
>     at insertBefore (http://localhost:3000/static/js/bundle.js:248365:22)
>     at insertOrAppendPlacementNode (http://localhost:3000/static/js/bundle.js:257654:11)
>     at insertOrAppendPlacementNode (http://localhost:3000/static/js/bundle.js:257664:13)
>     at insertOrAppendPlacementNode (http://localhost:3000/static/js/bundle.js:257661:11)
>     at insertOrAppendPlacementNode (http://localhost:3000/static/js/bundle.js:257661:11)
>     at commitPlacement (http://localhost:3000/static/js/bundle.js:257623:9)
>     at commitMutationEffects (http://localhost:3000/static/js/bundle.js:259492:15)
>     at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:242885:18)
>     at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:242929:20)
>     at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:242984:35)
> ```
> 
> which seems to go away by commenting out these lines image Did you experience something similar?

@enthusiastio can you please explain little bit better how the error can be reproduced because I tried to test it little bit better once more and couldn't find anything.

**Comment by enthusiastio** [comment]
> > Hi, I did not finish the review yet, but i encountered an error. That happens as soon as I click Add status change events
> > ```
> > react-dom.development.js:9035 Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
> >     at insertBefore (http://localhost:3000/static/js/bundle.js:248365:22)
> >     at insertOrAppendPlacementNode (http://localhost:3000/static/js/bundle.js:257654:11)
> >     at insertOrAppendPlacementNode (http://localhost:3000/static/js/bundle.js:257664:13)
> >     at insertOrAppendPlacementNode (http://localhost:3000/static/js/bundle.js:257661:11)
> >     at insertOrAppendPlacementNode (http://localhost:3000/static/js/bundle.js:257661:11)
> >     at commitPlacement (http://localhost:3000/static/js/bundle.js:257623:9)
> >     at commitMutationEffects (http://localhost:3000/static/js/bundle.js:259492:15)
> >     at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:242885:18)
> >     at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:242929:20)
> >     at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:242984:35)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > which seems to go away by commenting out these lines image Did you experience something similar?
> 
> @enthusiastio can you please explain little bit better how the error can be reproduced because I tried to test it little bit better once more and couldn't find anything.

I have found the issue was a conflict with one of the extensions https://chrome.google.com/webstore/detail/transover/aggiiclaiamajehmlfpkjmlbadmkledi
Having it installed errors when trying to save actions. I think we can ignore this, as this extension is not very popular.

**Review by enthusiastio — APPROVED** [review]
Looks good to me, @martin-trajanovski , congratulations on the big feature :100:

**Pull request merged**
