### PR TITLE
Allow Internal Reviewer to view PI name and email

### PR DESCRIPTION
**Pull request by RasmiaKulan**
## Description
Closes [980](https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/980)
The Internal Reviewer is granted access to view Principal Invetigators name and email.

## Motivation and Context
Initially the PI name and email columns were displaying empty values in the Internal Reviewer dashboard and only the Proposal Information was only displaying the PI name as shown below:

image

image

These changes allow the Internal Reviewer to view PI name and email in both the dashboard and the Proposal Information tab:

image

image

## How Has This Been Tested
Manually

## Fixes

[980](https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/980)
## Changes

Gave the Internal Reviewer role access to `UserQueries` and `BasicUserDetails` 
## Depends on

N/A

### CODE REVIEW

**Comment by simonfernandes** [comment]
Is `Internal Reviewer` role not STFC `Techincal Reviewer` then? Which proposal system role does `Technical Reviewer` have?

**Comment by Scott-James-Hurley** [comment]
> Is `Internal Reviewer` role not STFC `Techincal Reviewer` then? Which proposal system role does `Technical Reviewer` have?

An internal review is different from a technical review. An internal can be requested by a technical reviewer to add context and insight to a proposal that will inform the technical review, though it has no direct influence on a proposals score. In the context of STFC this will probably be used to request internal reviews by Deuteration. A technical reviewer has the `FAP Member` role. Correct me if I'm wrong.

**Comment by simonfernandes** [comment]
Thanks @Scott-James-Hurley, that's useful to know. So regular FAP members and technical reviewers both have the `FAP Member` role but the technical reviewer is assigned in the software itself on a per proposal basis

**Comment by Scott-James-Hurley** [comment]
A FAP member is a technical reviewer: they are one and the same . You are correct, they are assigned a proposal to review in the software and submit their technical review.

**Review by simonfernandes — APPROVED** [review]

**Comment by simonfernandes** [comment]
Thanks @TCMeldrum, do they still both use the same proposal system role of `FAP Reviewer`?

**Comment by TCMeldrum** [comment]
No Technical reviewers all should be instrument scientists and have that role

**Comment by simonfernandes** [comment]
Ok cool thanks, I'll stop derailing the PR now 😁 

I was originally trying to understand how this change relates to the original issue which is to hide the email from technical reviewers. But I guess this is fixing a bug on the side, and the original change is either done or yet to be done. This change looks good anyway

**Comment by Scott-James-Hurley** [comment]
@simonfernandes Sorry for leading you astray. I try to limit spreading misinformation online to my free time.

**Review by enthusiastio — APPROVED** [review]
Looks good :+1:

**Pull request merged**
